name: JoinStats
version: 1.0.1
api: [3.0.0, 4.0.0]
main: Eren5960\JoinStats\Loader
author: Eren5960
website: redmc.me
description: Track the number of players entering your server.

permissions:
    join.stats.command:
        description: Permission to use the /joinstats command
        default: op